# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Publish package to GitHub Packages

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version to build'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Set Release Version in pom.xml
        run: | 
          mvn versions:set -DnewVersion="${{github.event.inputs.release_version}}-SNAPSHOT"
          git add pom.xml
          git commit -m "Prepare release version ${{github.event.inputs.release_version}}"
          mvn release:prepare
          

      - name: Publish to GitHub Packages Apache Maven
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set SNAPSHOT Version in pom.xml
