name: Release Build

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version to build'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Prepare and deploy the release
        run: |
          git config --global user.email "roland.germ@gmail.com"
          git config --global user.name "rgerm"
          mvn --batch-mode -Dtag="v${{github.event.inputs.release_version}}" -DreleaseVersion="${{github.event.inputs.release_version}}" release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
